package FrontEndIDLInterface;


/**
* FrontEndIDLInterface/cal.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEndIDLInterface.idl
* Sunday, December 6, 2015 5:15:56 PM EST
*/

public final class cal implements org.omg.CORBA.portable.IDLEntity
{
  public int day = (int)0;
  public int month = (int)0;
  public int year = (int)0;

  public cal ()
  {
  } // ctor

  public cal (int _day, int _month, int _year)
  {
    day = _day;
    month = _month;
    year = _year;
  } // ctor

} // class cal
