package FrontEndIDLInterface;

/**
* FrontEndIDLInterface/calHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEndIDLInterface.idl
* Sunday, December 6, 2015 5:15:56 PM EST
*/

public final class calHolder implements org.omg.CORBA.portable.Streamable
{
  public FrontEndIDLInterface.cal value = null;

  public calHolder ()
  {
  }

  public calHolder (FrontEndIDLInterface.cal initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FrontEndIDLInterface.calHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FrontEndIDLInterface.calHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FrontEndIDLInterface.calHelper.type ();
  }

}
