package FrontEndIDLInterface;


/**
* FrontEndIDLInterface/customerInfoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEndIDLInterface.idl
* Sunday, December 6, 2015 5:15:56 PM EST
*/

abstract public class customerInfoHelper
{
  private static String  _id = "IDL:FrontEndIDLInterface/customerInfo:1.0";

  public static void insert (org.omg.CORBA.Any a, FrontEndIDLInterface.customerInfo that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FrontEndIDLInterface.customerInfo extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [1];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "customerInfo",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (FrontEndIDLInterface.customerInfoHelper.id (), "customerInfo", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FrontEndIDLInterface.customerInfo read (org.omg.CORBA.portable.InputStream istream)
  {
    FrontEndIDLInterface.customerInfo value = new FrontEndIDLInterface.customerInfo ();
    int _len0 = istream.read_long ();
    value.customerInfo = new String[_len0];
    for (int _o1 = 0;_o1 < value.customerInfo.length; ++_o1)
      value.customerInfo[_o1] = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FrontEndIDLInterface.customerInfo value)
  {
    ostream.write_long (value.customerInfo.length);
    for (int _i0 = 0;_i0 < value.customerInfo.length; ++_i0)
      ostream.write_string (value.customerInfo[_i0]);
  }

}
