package FrontEndIDLInterface;


/**
* FrontEndIDLInterface/customerInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEndIDLInterface.idl
* Sunday, December 6, 2015 5:15:56 PM EST
*/

public final class customerInfo implements org.omg.CORBA.portable.IDLEntity
{
  public String customerInfo[] = null;

  public customerInfo ()
  {
  } // ctor

  public customerInfo (String[] _customerInfo)
  {
    customerInfo = _customerInfo;
  } // ctor

} // class customerInfo
