package FrontEndIDLInterface;


/**
* FrontEndIDLInterface/frontEndIdlInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEndIDLInterface.idl
* Sunday, December 6, 2015 5:15:56 PM EST
*/

public interface frontEndIdlInterfaceOperations 
{
  String openAccount (String bank, String firstname, String lastname, String emailaddress, String phonenumber, String password);
  boolean getLoan (String bank, String accountnumber, String password, int loanAmount);
  boolean transferLoan (String loanID, String currentBank, String otherBank);
  boolean delayPayment (String bank, String loanID, FrontEndIDLInterface.cal currentDueDate, FrontEndIDLInterface.cal newDueDate);
  FrontEndIDLInterface.customerInfo printCustomerInfo (String bank);
} // interface frontEndIdlInterfaceOperations
