package FrontEndIDLInterface;


/**
* FrontEndIDLInterface/frontEndIdlInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEndIDLInterface.idl
* Sunday, December 6, 2015 5:15:56 PM EST
*/

public interface frontEndIdlInterface extends frontEndIdlInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface frontEndIdlInterface
