package FrontEndIDLInterface;


/**
* FrontEndIDLInterface/frontEndIdlInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEndIDLInterface.idl
* Sunday, December 6, 2015 5:15:56 PM EST
*/

abstract public class frontEndIdlInterfaceHelper
{
  private static String  _id = "IDL:FrontEndIDLInterface/frontEndIdlInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, FrontEndIDLInterface.frontEndIdlInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FrontEndIDLInterface.frontEndIdlInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (FrontEndIDLInterface.frontEndIdlInterfaceHelper.id (), "frontEndIdlInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FrontEndIDLInterface.frontEndIdlInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_frontEndIdlInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FrontEndIDLInterface.frontEndIdlInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static FrontEndIDLInterface.frontEndIdlInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FrontEndIDLInterface.frontEndIdlInterface)
      return (FrontEndIDLInterface.frontEndIdlInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FrontEndIDLInterface._frontEndIdlInterfaceStub stub = new FrontEndIDLInterface._frontEndIdlInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static FrontEndIDLInterface.frontEndIdlInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FrontEndIDLInterface.frontEndIdlInterface)
      return (FrontEndIDLInterface.frontEndIdlInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FrontEndIDLInterface._frontEndIdlInterfaceStub stub = new FrontEndIDLInterface._frontEndIdlInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
