package FrontEndIDLInterface;


/**
* FrontEndIDLInterface/frontEndIdlInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEndIDLInterface.idl
* Sunday, December 6, 2015 5:15:56 PM EST
*/

public abstract class frontEndIdlInterfacePOA extends org.omg.PortableServer.Servant
 implements FrontEndIDLInterface.frontEndIdlInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("openAccount", new java.lang.Integer (0));
    _methods.put ("getLoan", new java.lang.Integer (1));
    _methods.put ("transferLoan", new java.lang.Integer (2));
    _methods.put ("delayPayment", new java.lang.Integer (3));
    _methods.put ("printCustomerInfo", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // FrontEndIDLInterface/frontEndIdlInterface/openAccount
       {
         String bank = in.read_string ();
         String firstname = in.read_string ();
         String lastname = in.read_string ();
         String emailaddress = in.read_string ();
         String phonenumber = in.read_string ();
         String password = in.read_string ();
         String $result = null;
         $result = this.openAccount (bank, firstname, lastname, emailaddress, phonenumber, password);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // FrontEndIDLInterface/frontEndIdlInterface/getLoan
       {
         String bank = in.read_string ();
         String accountnumber = in.read_string ();
         String password = in.read_string ();
         int loanAmount = in.read_long ();
         boolean $result = false;
         $result = this.getLoan (bank, accountnumber, password, loanAmount);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // FrontEndIDLInterface/frontEndIdlInterface/transferLoan
       {
         String loanID = in.read_string ();
         String currentBank = in.read_string ();
         String otherBank = in.read_string ();
         boolean $result = false;
         $result = this.transferLoan (loanID, currentBank, otherBank);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // FrontEndIDLInterface/frontEndIdlInterface/delayPayment
       {
         String bank = in.read_string ();
         String loanID = in.read_string ();
         FrontEndIDLInterface.cal currentDueDate = FrontEndIDLInterface.frontEndIdlInterfacePackage.cHelper.read (in);
         FrontEndIDLInterface.cal newDueDate = FrontEndIDLInterface.frontEndIdlInterfacePackage.cHelper.read (in);
         boolean $result = false;
         $result = this.delayPayment (bank, loanID, currentDueDate, newDueDate);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // FrontEndIDLInterface/frontEndIdlInterface/printCustomerInfo
       {
         String bank = in.read_string ();
         FrontEndIDLInterface.customerInfo $result = null;
         $result = this.printCustomerInfo (bank);
         out = $rh.createReply();
         FrontEndIDLInterface.customerInfoHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:FrontEndIDLInterface/frontEndIdlInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public frontEndIdlInterface _this() 
  {
    return frontEndIdlInterfaceHelper.narrow(
    super._this_object());
  }

  public frontEndIdlInterface _this(org.omg.CORBA.ORB orb) 
  {
    return frontEndIdlInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class frontEndIdlInterfacePOA
