package FrontEndIDLInterface.frontEndIdlInterfacePackage;


/**
* FrontEndIDLInterface/frontEndIdlInterfacePackage/custInfoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEndIDLInterface.idl
* Sunday, December 6, 2015 5:15:56 PM EST
*/

abstract public class custInfoHelper
{
  private static String  _id = "IDL:FrontEndIDLInterface/frontEndIdlInterface/custInfo:1.0";

  public static void insert (org.omg.CORBA.Any a, FrontEndIDLInterface.customerInfo that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FrontEndIDLInterface.customerInfo extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = FrontEndIDLInterface.customerInfoHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (FrontEndIDLInterface.frontEndIdlInterfacePackage.custInfoHelper.id (), "custInfo", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FrontEndIDLInterface.customerInfo read (org.omg.CORBA.portable.InputStream istream)
  {
    FrontEndIDLInterface.customerInfo value = null;
    value = FrontEndIDLInterface.customerInfoHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FrontEndIDLInterface.customerInfo value)
  {
    FrontEndIDLInterface.customerInfoHelper.write (ostream, value);
  }

}
